version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks:
      - dev-network
    depends_on:
      - redis
      - service-a
      - service-b

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
    networks:
      - dev-network

  service-a:
    build:
      context: ../service-a
      dockerfile: ../.devcontainer/service.Dockerfile
    networks:
      - dev-network
    command: sh -c "cd src && python -m uvicorn main:app --host 0.0.0.0 --port 8000"

  service-b:
    build:
      context: ../service-b
      dockerfile: ../.devcontainer/service.Dockerfile
    networks:
      - dev-network
    command: sh -c "cd src && python -m uvicorn main:app --host 0.0.0.0 --port 8000"

networks:
  dev-network:
    driver: bridge